### ISSUE TITLE
Q: wonder why make this plugin but not make those functions built-in

### ISSUE THREAD

**Issue by isvicy** [nvim-telescope/telescope-fzf-writer.nvim#2]
Looks like this plugin is the improved and more easily customized version of live_grep and find_files of telescope.

Just curious why these functions are put into a separate plug-in instead of directly built-in.

**Comment by Conni2461** [comment]
Okay i give this one a try.

1. We tj put up this extension it was like the second one and it was kinda functioning as a way to make sure tjs extension interface works as expected.
2. We defined Extensions very loosely in some thread as more finder definition which need something else to function. Like `telescope-dap.nvim` require `dap.nvim`, this one requires fzf. And if we put that in core and replace `live_grep` and `find_files` people need `fzf` now and i think some people actually moved on and removed fzf from their machines.

**Comment by isvicy** [comment]
thanks for your explanation. sounds reasonable.
